/*
 * Copyright (C) 2020 Intel Corporation
 * SPDX-License-Identifier: BSD-3-Clause
 */

package controllers_test

import (
	"crypto/tls"
	"crypto/x509"
	"github.com/gorilla/mux"
	"github.com/intel-secl/intel-secl/v3/pkg/kbs/config"
	"github.com/intel-secl/intel-secl/v3/pkg/kbs/controllers"
	"github.com/intel-secl/intel-secl/v3/pkg/kbs/domain/mocks"
	"github.com/intel-secl/intel-secl/v3/pkg/kbs/keymanager"
	kbsRoutes "github.com/intel-secl/intel-secl/v3/pkg/kbs/router"
	consts "github.com/intel-secl/intel-secl/v3/pkg/lib/common/constants"
	"github.com/intel-secl/intel-secl/v3/pkg/lib/common/crypt"
	. "github.com/onsi/ginkgo"
	. "github.com/onsi/gomega"
	"github.com/onsi/gomega/ghttp"
	"io/ioutil"
	"net/http"
	"net/http/httptest"
	"strings"
)

var _ = Describe("SKCKeyTransferController", func() {
	var router *mux.Router
	var server *ghttp.Server
	var w *httptest.ResponseRecorder
	var keyStore *mocks.MockKeyStore
	var policyStore *mocks.MockKeyTransferPolicyStore
	var remoteManager *keymanager.RemoteManager
	var skcController *controllers.SKCController
	var kbsConfig *config.Configuration
	var cert *x509.Certificate
	var cs tls.ConnectionState

	BeforeEach(func() {
		router = mux.NewRouter()
		server = ghttp.NewServer()
		keyStore = mocks.NewFakeKeyStore()
		policyStore = mocks.NewFakeKeyTransferPolicyStore()
		kbsConfig = &config.Configuration{
			AASApiUrl: "http://" + server.Addr() + "/aas/",
			KBS: config.KBSConfig{
				UserName: KBSServiceUserName,
				Password: KBSServicePassword,
			},
			Skc: config.SKCConfig{
				StmLabel: "SGX",
				SQVSUrl:  "http://" + server.Addr() + "/svs/v1",
			},
		}

		certPem, _ := ioutil.ReadFile(skcClientCertPath)
		cert, _ = crypt.GetCertFromPem(certPem)
		cs.PeerCertificates = append(cs.PeerCertificates, cert)

		keyManager := &keymanager.DirectoryManager{}
		remoteManager = keymanager.NewRemoteManager(keyStore, keyManager, endpointUrl)
		skcController = controllers.NewSKCController(remoteManager, policyStore, kbsConfig, trustedCaCertsDir)
		setupServer(server)
	})

	AfterEach(func() {
		server.Close()
	})

	// Specs for HTTP GET to "/dhsm2-transfer"
	Describe("Transfers an existing Key", func() {
		Context("Provide a valid Transfer request", func() {
			BeforeEach(func() {
				sessionController := controllers.NewSessionController(kbsConfig, trustedCaCertsDir)
				router.Handle("/session", kbsRoutes.ErrorHandler(kbsRoutes.JsonResponseHandler(sessionController.Create))).Methods("POST")
				sessionJson := `{
									"challenge_type": "SGX",
									"challenge": "MTRjZmNlZDEtMDNlZS00YTY4LThiNTAtNmQ0NTY0MjNiMDc4",
									"quote": "AQAAAAAAAAB7EwAAAQAAAAEAAAADAAAAAAEAANwGAAAtLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJRTZEQ0NCSTZnQXdJQkFnSVZBS1dDV0J2ZUwrMGM5Z3llT3VnU2x0MFh5alF3TUFvR0NDcUdTTTQ5QkFNQ01IQXhJakFnQmdOVgpCQU1NR1VsdWRHVnNJRk5IV0NCUVEwc2dVR3hoZEdadmNtMGdRMEV4R2pBWUJnTlZCQW9NRVVsdWRHVnNJRU52Y25CdmNtRjBhVzl1Ck1SUXdFZ1lEVlFRSERBdFRZVzUwWVNCRGJHRnlZVEVMTUFrR0ExVUVDQXdDUTBFeEN6QUpCZ05WQkFZVEFsVlRNQjRYRFRJd01UQXkKTVRBNE5EQXdNMW9YRFRJM01UQXlNVEE0TkRBd00xb3djREVpTUNBR0ExVUVBd3daU1c1MFpXd2dVMGRZSUZCRFN5QkRaWEowYVdacApZMkYwWlRFYU1CZ0dBMVVFQ2d3UlNXNTBaV3dnUTI5eWNHOXlZWFJwYjI0eEZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3CkNRWURWUVFJREFKRFFURUxNQWtHQTFVRUJoTUNWVk13V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVM5ZkIzRklUSjcKc2dyMkg5b2Vxd0htbTRUc3ErZ0Z2SURJVFJ3T2IxNkNHOWVPVHpBOFVWWi9aNDFFNFg1U1pkd0V5Nnp0MHdTVEJXRzVMTEFHazlBMgpvNElEQXpDQ0F2OHdId1lEVlIwakJCZ3dGb0FVV1NQVHAwcW9ZMVF1T1hDdDRBOEhLMWNrS3Jjd1lnWURWUjBmQkZzd1dUQlhvRldnClU0WlJhSFIwY0hNNkx5OXpZbmd1WVhCcExuUnlkWE4wWldSelpYSjJhV05sY3k1cGJuUmxiQzVqYjIwdmMyZDRMMk5sY25ScFptbGoKWVhScGIyNHZkak12Y0dOclkzSnNQMk5oUFhCc1lYUm1iM0p0TUIwR0ExVWREZ1FXQkJSeVdOaElxZzVydXZoTk04ZUM5cHoyaVhNVApLVEFPQmdOVkhROEJBZjhFQkFNQ0JzQXdEQVlEVlIwVEFRSC9CQUl3QURDQ0Fqa0dDU3FHU0liNFRRRU5BUVNDQWlvd2dnSW1NQjRHCkNpcUdTSWI0VFFFTkFRRUVFSVUvbUhScGFvSVZPVTlYalJMRFEwd3dnZ0ZqQmdvcWhraUcrRTBCRFFFQ01JSUJVekFRQmdzcWhraUcKK0UwQkRRRUNBUUlCQWpBUUJnc3Foa2lHK0UwQkRRRUNBZ0lCQWpBUUJnc3Foa2lHK0UwQkRRRUNBd0lCQURBUUJnc3Foa2lHK0UwQgpEUUVDQkFJQkFEQVFCZ3NxaGtpRytFMEJEUUVDQlFJQkFEQVFCZ3NxaGtpRytFMEJEUUVDQmdJQkFEQVFCZ3NxaGtpRytFMEJEUUVDCkJ3SUJBREFRQmdzcWhraUcrRTBCRFFFQ0NBSUJBREFRQmdzcWhraUcrRTBCRFFFQ0NRSUJBREFRQmdzcWhraUcrRTBCRFFFQ0NnSUIKQURBUUJnc3Foa2lHK0UwQkRRRUNDd0lCQURBUUJnc3Foa2lHK0UwQkRRRUNEQUlCQURBUUJnc3Foa2lHK0UwQkRRRUNEUUlCQURBUQpCZ3NxaGtpRytFMEJEUUVDRGdJQkFEQVFCZ3NxaGtpRytFMEJEUUVDRHdJQkFEQVFCZ3NxaGtpRytFMEJEUUVDRUFJQkFEQVFCZ3NxCmhraUcrRTBCRFFFQ0VRSUJDakFmQmdzcWhraUcrRTBCRFFFQ0VnUVFBZ0lBQUFBQUFBQUFBQUFBQUFBQUFEQVFCZ29xaGtpRytFMEIKRFFFREJBSUFBREFVQmdvcWhraUcrRTBCRFFFRUJBWWdZR29BQUFBd0R3WUtLb1pJaHZoTkFRMEJCUW9CQVRBZUJnb3Foa2lHK0UwQgpEUUVHQkJDazhXaUoyaXBHcFZ4NGFjUFN2UGRtTUVRR0NpcUdTSWI0VFFFTkFRY3dOakFRQmdzcWhraUcrRTBCRFFFSEFRRUIvekFRCkJnc3Foa2lHK0UwQkRRRUhBZ0VCQURBUUJnc3Foa2lHK0UwQkRRRUhBd0VCL3pBS0JnZ3Foa2pPUFFRREFnTklBREJGQWlCbFdEQ2QKLzRuMEtuNjhpd2VrWXBSUndyTWk3aDk4UVljQ3FvL3ZnTThOR1FJaEFPZ1JKR3F1WWtXSGhhV2kyNmo5Qm5MOTk1YXVBNHh1NWUycgpFWEVQZ0hheAotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tAQAB7D7ceJTRta+avIIlxbl8kTrZsWb+joxZ0YBW80wi5H5NCG30xvXt0HUTk5pt/561H/KWq7zZ7qos7pP8zk3h68XjB5iRCL3kpCYFGCku+wKF9ifjucB95wZAMQHXe8ASuWfAu0wp+nnlHmZ1GOe3jyBNkpg5JWaCYio1KQrTkOeSEmfG6HsNSNgpeVwb9Clv+07Gzme/slfRIBgaqCxxj31tYVTjdnQAIdMeu12bKY/ky9uN0T6pMpH16B8QqMCqwAJ1/SrqjWCDnMmVXCLL3bsbuyiiPWW7nneY1Koav9fSXRIsGwBbsjhIhTo/UTLCNWB90Msg8vriQojogi+b+QMAAgAAAAAABQAKAJOacjP3nEyplAoNs5V/Bgf7U4FObrPpa0TdQGoGAVtMAAAAAAICAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAcAAAAAAAAA5wAAAAAAAAB98LfoFb1LSvQSOQONBKdA2szwvrQSogVsjZALRbYh/QAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAzRccVpQcbOSWkLRV9pHZyKBMLkPgpNMPdS+lKFx+5X8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAe/LDs+R3S/EkblXvOzq3Sm/B7e5WzAoqwrFsgR+VV9oAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAMQQAAD3tZb1saku5m+kPNK1gZz+gwRTlHTSIk0ofrU3zxoEONcO08rvYq1ahUPnFD8oLN8AMeElqFxcbuaN7kI1XuyGRFiUopkYEiiToB7XZJ0vcc6o3/19XCmD0bAWAsVB2fyAzPde/VdTqeA8c8c2mi1gzFwm/KEG9KkQ3rY80ziG1QICAAEBAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABUAAAAAAAAA5wAAAAAAAABg2Fryi+jRxAoI2YsAnV+KzBOEo4XPRggA5Hh5HRqXnAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAjE9XddeWUD6WE393xoqCmgBWrI3tcBQLCBsJRJDFe/8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAABAAUAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAV71m8uepU0A4bk9rbHOW4HKV9es+vkWhAPiFPelpo8sAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAL31cBgIvkUsoxU38bIijBfDtWsE8gPZL+OwXhXMWr4c5Lwr26cZREggx4cVdDFHgNyi8YOT64Fbcx2/g0aFiFsgAAABAgMEBQYHCAkKCwwNDg8QERITFBUWFxgZGhscHR4fBQBcDgAALS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUU2RENDQkk2Z0F3SUJBZ0lWQUtXQ1dCdmVMKzBjOWd5ZU91Z1NsdDBYeWpRd01Bb0dDQ3FHU000OUJBTUNNSEF4SWpBZ0JnTlYKQkFNTUdVbHVkR1ZzSUZOSFdDQlFRMHNnVUd4aGRHWnZjbTBnUTBFeEdqQVlCZ05WQkFvTUVVbHVkR1ZzSUVOdmNuQnZjbUYwYVc5dQpNUlF3RWdZRFZRUUhEQXRUWVc1MFlTQkRiR0Z5WVRFTE1Ba0dBMVVFQ0F3Q1EwRXhDekFKQmdOVkJBWVRBbFZUTUI0WERUSXdNVEF5Ck1UQTROREF3TTFvWERUSTNNVEF5TVRBNE5EQXdNMW93Y0RFaU1DQUdBMVVFQXd3WlNXNTBaV3dnVTBkWUlGQkRTeUJEWlhKMGFXWnAKWTJGMFpURWFNQmdHQTFVRUNnd1JTVzUwWld3Z1EyOXljRzl5WVhScGIyNHhGREFTQmdOVkJBY01DMU5oYm5SaElFTnNZWEpoTVFzdwpDUVlEVlFRSURBSkRRVEVMTUFrR0ExVUVCaE1DVlZNd1dUQVRCZ2NxaGtqT1BRSUJCZ2dxaGtqT1BRTUJCd05DQUFTOWZCM0ZJVEo3CnNncjJIOW9lcXdIbW00VHNxK2dGdklESVRSd09iMTZDRzllT1R6QThVVlovWjQxRTRYNVNaZHdFeTZ6dDB3U1RCV0c1TExBR2s5QTIKbzRJREF6Q0NBdjh3SHdZRFZSMGpCQmd3Rm9BVVdTUFRwMHFvWTFRdU9YQ3Q0QThISzFja0tyY3dZZ1lEVlIwZkJGc3dXVEJYb0ZXZwpVNFpSYUhSMGNITTZMeTl6WW5ndVlYQnBMblJ5ZFhOMFpXUnpaWEoyYVdObGN5NXBiblJsYkM1amIyMHZjMmQ0TDJObGNuUnBabWxqCllYUnBiMjR2ZGpNdmNHTnJZM0pzUDJOaFBYQnNZWFJtYjNKdE1CMEdBMVVkRGdRV0JCUnlXTmhJcWc1cnV2aE5NOGVDOXB6MmlYTVQKS1RBT0JnTlZIUThCQWY4RUJBTUNCc0F3REFZRFZSMFRBUUgvQkFJd0FEQ0NBamtHQ1NxR1NJYjRUUUVOQVFTQ0Fpb3dnZ0ltTUI0RwpDaXFHU0liNFRRRU5BUUVFRUlVL21IUnBhb0lWT1U5WGpSTERRMHd3Z2dGakJnb3Foa2lHK0UwQkRRRUNNSUlCVXpBUUJnc3Foa2lHCitFMEJEUUVDQVFJQkFqQVFCZ3NxaGtpRytFMEJEUUVDQWdJQkFqQVFCZ3NxaGtpRytFMEJEUUVDQXdJQkFEQVFCZ3NxaGtpRytFMEIKRFFFQ0JBSUJBREFRQmdzcWhraUcrRTBCRFFFQ0JRSUJBREFRQmdzcWhraUcrRTBCRFFFQ0JnSUJBREFRQmdzcWhraUcrRTBCRFFFQwpCd0lCQURBUUJnc3Foa2lHK0UwQkRRRUNDQUlCQURBUUJnc3Foa2lHK0UwQkRRRUNDUUlCQURBUUJnc3Foa2lHK0UwQkRRRUNDZ0lCCkFEQVFCZ3NxaGtpRytFMEJEUUVDQ3dJQkFEQVFCZ3NxaGtpRytFMEJEUUVDREFJQkFEQVFCZ3NxaGtpRytFMEJEUUVDRFFJQkFEQVEKQmdzcWhraUcrRTBCRFFFQ0RnSUJBREFRQmdzcWhraUcrRTBCRFFFQ0R3SUJBREFRQmdzcWhraUcrRTBCRFFFQ0VBSUJBREFRQmdzcQpoa2lHK0UwQkRRRUNFUUlCQ2pBZkJnc3Foa2lHK0UwQkRRRUNFZ1FRQWdJQUFBQUFBQUFBQUFBQUFBQUFBREFRQmdvcWhraUcrRTBCCkRRRURCQUlBQURBVUJnb3Foa2lHK0UwQkRRRUVCQVlnWUdvQUFBQXdEd1lLS29aSWh2aE5BUTBCQlFvQkFUQWVCZ29xaGtpRytFMEIKRFFFR0JCQ2s4V2lKMmlwR3BWeDRhY1BTdlBkbU1FUUdDaXFHU0liNFRRRU5BUWN3TmpBUUJnc3Foa2lHK0UwQkRRRUhBUUVCL3pBUQpCZ3NxaGtpRytFMEJEUUVIQWdFQkFEQVFCZ3NxaGtpRytFMEJEUUVIQXdFQi96QUtCZ2dxaGtqT1BRUURBZ05JQURCRkFpQmxXRENkCi80bjBLbjY4aXdla1lwUlJ3ck1pN2g5OFFZY0Nxby92Z004TkdRSWhBT2dSSkdxdVlrV0hoYVdpMjZqOUJuTDk5NWF1QTR4dTVlMnIKRVhFUGdIYXgKLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLS0tLS0tQkVHSU4gQ0VSVElGSUNBVEUtLS0tLQpNSUlDbXpDQ0FrQ2dBd0lCQWdJVVdTUFRwMHFvWTFRdU9YQ3Q0QThISzFja0tyY3dDZ1lJS29aSXpqMEVBd0l3CmFERWFNQmdHQTFVRUF3d1JTVzUwWld3Z1UwZFlJRkp2YjNRZ1EwRXhHakFZQmdOVkJBb01FVWx1ZEdWc0lFTnYKY25CdmNtRjBhVzl1TVJRd0VnWURWUVFIREF0VFlXNTBZU0JEYkdGeVlURUxNQWtHQTFVRUNBd0NRMEV4Q3pBSgpCZ05WQkFZVEFsVlRNQjRYRFRFNU1UQXpNVEV5TXpRek1Wb1hEVE0wTVRBek1URXlNelF6TVZvd2NERWlNQ0FHCkExVUVBd3daU1c1MFpXd2dVMGRZSUZCRFN5QlFiR0YwWm05eWJTQkRRVEVhTUJnR0ExVUVDZ3dSU1c1MFpXd2cKUTI5eWNHOXlZWFJwYjI0eEZEQVNCZ05WQkFjTUMxTmhiblJoSUVOc1lYSmhNUXN3Q1FZRFZRUUlEQUpEUVRFTApNQWtHQTFVRUJoTUNWVk13V1RBVEJnY3Foa2pPUFFJQkJnZ3Foa2pPUFFNQkJ3TkNBQVF3cCtMYytUVUJ0ZzFICitVOEpJc01zYmpIakNrVHRYYjhqUE02cjJkaHU5eklibGhEWjdJTmZxdDNJeDhYY0ZLRDhrME5FWHJrWjY2cUoKWGExS3pMSUtvNEcvTUlHOE1COEdBMVVkSXdRWU1CYUFGT25vUkZKVE5seExHSm9SL0VNWUxLWGNJSUJJTUZZRwpBMVVkSHdSUE1FMHdTNkJKb0VlR1JXaDBkSEJ6T2k4dmMySjRMV05sY25ScFptbGpZWFJsY3k1MGNuVnpkR1ZrCmMyVnlkbWxqWlhNdWFXNTBaV3d1WTI5dEwwbHVkR1ZzVTBkWVVtOXZkRU5CTG1OeWJEQWRCZ05WSFE0RUZnUVUKV1NQVHAwcW9ZMVF1T1hDdDRBOEhLMWNrS3Jjd0RnWURWUjBQQVFIL0JBUURBZ0VHTUJJR0ExVWRFd0VCL3dRSQpNQVlCQWY4Q0FRQXdDZ1lJS29aSXpqMEVBd0lEU1FBd1JnSWhBSVJvWHUzWTQ1VkY5YUNpSzBaMks2RVFLQ3RDCnJ4VFRpWjRKWWJFeWZCR3NBaUVBaVZvWW14RjdLL1NvcUlqZmYxekcwL0xpdi9SSU9SL1FCSjUrZDg4SEFZST0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQotLS0tLUJFR0lOIENFUlRJRklDQVRFLS0tLS0KTUlJQ2xEQ0NBam1nQXdJQkFnSVZBT25vUkZKVE5seExHSm9SL0VNWUxLWGNJSUJJTUFvR0NDcUdTTTQ5QkFNQwpNR2d4R2pBWUJnTlZCQU1NRVVsdWRHVnNJRk5IV0NCU2IyOTBJRU5CTVJvd0dBWURWUVFLREJGSmJuUmxiQ0JECmIzSndiM0poZEdsdmJqRVVNQklHQTFVRUJ3d0xVMkZ1ZEdFZ1EyeGhjbUV4Q3pBSkJnTlZCQWdNQWtOQk1Rc3cKQ1FZRFZRUUdFd0pWVXpBZUZ3MHhPVEV3TXpFd09UUTVNakZhRncwME9URXlNekV5TXpVNU5UbGFNR2d4R2pBWQpCZ05WQkFNTUVVbHVkR1ZzSUZOSFdDQlNiMjkwSUVOQk1Sb3dHQVlEVlFRS0RCRkpiblJsYkNCRGIzSndiM0poCmRHbHZiakVVTUJJR0ExVUVCd3dMVTJGdWRHRWdRMnhoY21FeEN6QUpCZ05WQkFnTUFrTkJNUXN3Q1FZRFZRUUcKRXdKVlV6QlpNQk1HQnlxR1NNNDlBZ0VHQ0NxR1NNNDlBd0VIQTBJQUJFLzZELzFXSE5yV3dQbU5NSXlCS01XNQpKNkp6TXNqbzZ4UDJ2a0sxY2RaR2IxUEdSUC9DLzhFQ2dpRGtta2xtendMekxpKzAwMG03TExydEtKQTNvQzJqCmdiOHdnYnd3SHdZRFZSMGpCQmd3Rm9BVTZlaEVVbE0yWEVzWW1oSDhReGdzcGR3Z2dFZ3dWZ1lEVlIwZkJFOHcKVFRCTG9FbWdSNFpGYUhSMGNITTZMeTl6WW5ndFkyVnlkR2xtYVdOaGRHVnpMblJ5ZFhOMFpXUnpaWEoyYVdObApjeTVwYm5SbGJDNWpiMjB2U1c1MFpXeFRSMWhTYjI5MFEwRXVZM0pzTUIwR0ExVWREZ1FXQkJUcDZFUlNVelpjClN4aWFFZnhER0N5bDNDQ0FTREFPQmdOVkhROEJBZjhFQkFNQ0FRWXdFZ1lEVlIwVEFRSC9CQWd3QmdFQi93SUIKQVRBS0JnZ3Foa2pPUFFRREFnTkpBREJHQWlFQTBSV3JzR3JHbERwNzZsOUxRanQrek1xUVpQQi8yWXV1dWVGVQpnTjlBZGtNQ0lRRG85QU5VaGNTdEFCQ2hSNnJsVm9CbzZNUTZRdW1DbmsrcGRHQkV5OC9zUWc9PQotLS0tLUVORCBDRVJUSUZJQ0FURS0tLS0tCg=="
								}`
				req, err := http.NewRequest(
					"POST",
					"/session",
					strings.NewReader(sessionJson),
				)
				req.Header.Set("Accept", consts.HTTPMediaTypeJson)
				req.Header.Set("Content-Type", consts.HTTPMediaTypeJson)
				Expect(err).NotTo(HaveOccurred())
				w = httptest.NewRecorder()
				router.ServeHTTP(w, req)
				Expect(w.Code).To(Equal(http.StatusCreated))
			})
			It("Should transfer an existing Key", func() {
				router.Handle("/keys/{id}/dhsm2-transfer", kbsRoutes.ErrorHandler(kbsRoutes.JsonResponseHandler(skcController.TransferApplicationKey))).Methods("GET")
				req, err := http.NewRequest("GET", "/keys/ee37c360-7eae-4250-a677-6ee12adce8e2/dhsm2-transfer", nil)
				req.Header.Set("Accept", consts.HTTPMediaTypeJson)
				req.Header.Set("Accept-Challenge", "SGX")
				req.Header.Set("Session-Id", "SGX:14cfced1-03ee-4a68-8b50-6d456423b078")
				req.TLS = &cs
				Expect(err).NotTo(HaveOccurred())
				w = httptest.NewRecorder()
				router.ServeHTTP(w, req)
				Expect(w.Code).To(Equal(http.StatusOK))
			})
		})
		Context("Provide a Transfer request without Accept-Challenge Header", func() {
			It("Should fail to transfer an existing Key", func() {
				router.Handle("/keys/{id}/dhsm2-transfer", kbsRoutes.ErrorHandler(kbsRoutes.JsonResponseHandler(skcController.TransferApplicationKey))).Methods("GET")
				req, err := http.NewRequest("GET", "/keys/ee37c360-7eae-4250-a677-6ee12adce8e2/dhsm2-transfer", nil)
				req.Header.Set("Accept", consts.HTTPMediaTypeJson)
				req.Header.Set("Session-Id", "SGX:14cfced1-03ee-4a68-8b50-6d456423b078")
				req.TLS = &cs
				Expect(err).NotTo(HaveOccurred())
				w = httptest.NewRecorder()
				router.ServeHTTP(w, req)
				Expect(w.Code).To(Equal(http.StatusBadRequest))
			})
		})
		Context("Provide a Transfer request without Session-Id Header", func() {
			It("Should fail to transfer an existing Key", func() {
				router.Handle("/keys/{id}/dhsm2-transfer", kbsRoutes.ErrorHandler(kbsRoutes.JsonResponseHandler(skcController.TransferApplicationKey))).Methods("GET")
				req, err := http.NewRequest("GET", "/keys/ee37c360-7eae-4250-a677-6ee12adce8e2/dhsm2-transfer", nil)
				req.Header.Set("Accept", consts.HTTPMediaTypeJson)
				req.Header.Set("Accept-Challenge", "SGX")
				req.TLS = &cs
				Expect(err).NotTo(HaveOccurred())
				w = httptest.NewRecorder()
				router.ServeHTTP(w, req)
				Expect(w.Code).To(Equal(http.StatusUnauthorized))
			})
		})
	})
})
